version: '3'
services:
  server:
    command: "nodemon -L index.js"
    build:
      context: ./
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
volumes:
  redis-data: